export const fullGame = {
  0: {
    roll1: 1,
    roll2: 2,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  1: {
    roll1: 3,
    roll2: 4,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  2: {
    roll1: 5,
    roll2: 5,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  3: {
    roll1: 6,
    roll2: 3,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  4: {
    roll1: 10,
    roll2: null,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  5: {
    roll1: 7,
    roll2: 3,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  6: {
    roll1: 9,
    roll2: 1,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  7: {
    roll1: 6,
    roll2: 2,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  8: {
    roll1: 5,
    roll2: 3,
    roll3: null,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
  9: {
    roll1: 10,
    roll2: 1,
    roll3: 9,
    additionalRoll1: null,
    additionalRoll2: null,
    cumulativeScore: null,
  },
};
